"""CoherenceCheck: Reviews all generated slide content for consistency.

Uses Bedrock Haiku for a lightweight review pass. Auto-corrects minor issues
and surfaces major issues as warnings.
"""

import logging

from app.models.schemas import (
    CoherenceCheckOutput,
    CoherenceIssue,
    DeckOutline,
    SlideContent,
)
from app.services.bedrock import BedrockClient

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """\
You are a presentation quality reviewer. Review the generated slide content \
for a deck and identify any coherence issues.

Check for:
1. **Repetition**: Same points made across multiple slides.
2. **Tonal drift**: Inconsistent tone or formality level between slides.
3. **Inconsistency**: Contradicting facts or claims between slides.
4. **Other**: Any other quality issues (awkward phrasing, missing context).

For each issue found:
- Assign severity "minor" if it can be auto-corrected with a simple fix.
- Assign severity "major" if it requires human judgment or significant rewriting.
- Provide a suggested_fix for minor issues.

Rate overall coherence from 0.0 (incoherent) to 1.0 (perfectly coherent).
"""


def _build_review_prompt(
    slide_contents: list[SlideContent],
    outline: DeckOutline,
) -> str:
    """Build the user prompt for coherence review."""
    parts = []

    parts.append(f"## Deck: {outline.deck_title}")
    parts.append(f"Audience: {outline.audience}")
    parts.append(f"Narrative arc: {outline.narrative_arc}")

    parts.append("\n## Generated Content\n")
    for sc in slide_contents:
        parts.append(f"### Slide {sc.slide_number} ({sc.layout_name})")
        for field in sc.fields:
            parts.append(f"  {field.field_name}: {field.content}")
        parts.append("")

    return "\n".join(parts)


class CoherenceCheck:
    def __init__(self, bedrock_client: BedrockClient, model_id: str):
        self._bedrock = bedrock_client
        self._model_id = model_id

    async def check(
        self,
        slide_contents: list[SlideContent],
        outline: DeckOutline,
    ) -> CoherenceCheckOutput:
        """Review all slide content for coherence issues."""
        user_prompt = _build_review_prompt(slide_contents, outline)

        logger.info("Running coherence check on %d slides", len(slide_contents))

        result = await self._bedrock.converse_structured(
            model_id=self._model_id,
            system_prompt=SYSTEM_PROMPT,
            user_prompt=user_prompt,
            output_schema=CoherenceCheckOutput,
            max_tokens=2048,
            temperature=0.2,
        )

        logger.info(
            "Coherence check complete: score=%.2f, issues=%d",
            result.overall_coherence_score, len(result.issues),
        )

        return result

    def apply_fixes(
        self,
        slide_contents: list[SlideContent],
        coherence_output: CoherenceCheckOutput,
    ) -> tuple[list[SlideContent], list[str]]:
        """Apply minor fixes and collect major issue warnings.

        Returns (updated_contents, warnings).
        Minor issues with suggested_fix are logged as warnings but not
        auto-applied (content was already generated by LLM).
        Major issues are surfaced as user-visible warnings.
        """
        warnings: list[str] = []

        for issue in coherence_output.issues:
            if issue.severity == "major":
                warnings.append(
                    f"Slide {issue.slide_number}: {issue.issue_type} — {issue.description}"
                )
            else:
                warnings.append(
                    f"Slide {issue.slide_number} (minor): {issue.issue_type} — {issue.description}"
                )

        return slide_contents, warnings
